name: Test Wonderful Toolchain Installer

on:
  workflow_dispatch:

jobs:
  test-installer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v6
        with:
            python-version: '3.12'
    
      - name: Install Python dependencies
        run: pip install pillow
      
      - name: Test wonderful toolchain installer
        run: |
          curl -fsSL https://bread.codes/scripts/wonderful-linux.sh | bash
          source /opt/wonderful/bin/wf-env
          git clone https://github.com/breadbored/butano-tutorial-series.git butano-tutorial-series
          cd butano-tutorial-series
          git submodule update --init --recursive
          cd chapter-1-getting-started
          make
          if [ ! -f chapter-1-getting-started.gba ]; then
              echo "chapter-1-getting-started.gba does not exist!"
              exit 1
          fi