name: Test Wonderful Toolchain Installer

on:
  workflow_dispatch:

jobs:
  test-installer:
    runs-on: ubuntu-latest
    steps:
      - name: Test wonderful toolchain installer
        run: curl -fsSL https://bread.codes/scripts/wonderful-linux.sh | bash

      - name: Pull example repository
        run: git clone https://github.com/breadbored/butano-tutorial-series.git butano-tutorial-series
    
      - name: Build example repository
        run: |
          cd butano-tutorial-series/chapter-1-getting-started
          make
          if [ ! -f chapter-1-getting-started.gba ]; then
              echo "chapter-1-getting-started.gba does not exist!"
              exit 1
          fi